/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { SearchTokenHttpType } from './searchTokenHttpType';

export interface SearchTokenHttp {
  createdAt: string;
  id: string;
  token: string;
  type: SearchTokenHttpType;
}
