/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { UserHttpAvatarImageUrl } from './userHttpAvatarImageUrl';
import type { UserHttpRole } from './userHttpRole';

export interface UserHttp {
  avatarImageId: string;
  /** @nullable */
  avatarImageUrl: UserHttpAvatarImageUrl;
  email: string;
  finishedWorksCount: number;
  id: string;
  name: string;
  notionDatabaseId?: string;
  readingWorksCount: number;
  role: UserHttpRole;
}
