/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { TagModel } from './tagModel';

export interface WorkHttp {
  category: string;
  chapter: number;
  hasNewChapter: boolean;
  id: string;
  imageId: string;
  /** @nullable */
  imageUrl: string | null;
  isDropped: boolean;
  isFinished: boolean;
  name: string;
  /** @nullable */
  nextChapter: number | null;
  /** @nullable */
  nextChapterUpdatedAt: string | null;
  refreshStatus: string;
  tags: TagModel[];
  updatedAt: string;
  url: string;
  userId: string;
}
