/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type _CustomListModelTypename = typeof _CustomListModelTypename[keyof typeof _CustomListModelTypename];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _CustomListModelTypename = {
  'custom-list': 'custom-list',
} as const;
