/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type _ScrappingReportWorkModelTypename = typeof _ScrappingReportWorkModelTypename[keyof typeof _ScrappingReportWorkModelTypename];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _ScrappingReportWorkModelTypename = {
  work: 'work',
} as const;
