/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type _WorkHttpTypename = typeof _WorkHttpTypename[keyof typeof _WorkHttpTypename];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _WorkHttpTypename = {
  work: 'work',
} as const;
