/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type AddRowInCalendarDtoDayOfWeek = typeof AddRowInCalendarDtoDayOfWeek[keyof typeof AddRowInCalendarDtoDayOfWeek];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddRowInCalendarDtoDayOfWeek = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const;
