/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { CalendarRowModel } from './calendarRowModel';

export interface CalendarModel {
  createdAt: string;
  /** @nullable */
  description: string | null;
  rows: CalendarRowModel[];
  title: string;
}
