/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type CreateSearchTokenDtoType =
	(typeof CreateSearchTokenDtoType)[keyof typeof CreateSearchTokenDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSearchTokenDtoType = {
	ANIME: "ANIME",
	MANGA: "MANGA",
} as const;
