/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export interface CreateCustomListDto {
  description?: string;
  title: string;
  worksId: string[];
}
