/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { _CustomListWithWorksModelTypename } from './_customListWithWorksModelTypename';
import type { WorkHttp } from './workHttp';

export interface CustomListWithWorksModel {
  /** */
  readonly __typename: _CustomListWithWorksModelTypename;
  count: number;
  description?: string;
  id: string;
  isShared: boolean;
  publicId: string;
  /** @nullable */
  thumbnailImageId?: string | null;
  /** @nullable */
  thumbnailImageUrl: string | null;
  title: string;
  works: WorkHttp[];
}
