/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { _CustomListModelTypename } from './_customListModelTypename';

export interface CustomListModel {
  /** */
  readonly __typename: _CustomListModelTypename;
  description?: string;
  id: string;
  ownerId: string;
  title: string;
}
