/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { FetchSharedWorkOwner } from './fetchSharedWorkOwner';
import type { FetchSharedWork } from './fetchSharedWork';

export interface FetchSharedWorkQueryResponse {
  /** Details of the owner */
  owner: FetchSharedWorkOwner;
  /** Unique identifier of the shared work */
  publicId: string;
  /** Details of the work */
  work: FetchSharedWork;
}
