/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { FetchSharedWorkTag } from './fetchSharedWorkTag';

export interface FetchSharedWork {
  /** Alternative name of the work */
  alternativeName: string;
  /** Category of the work */
  category: string;
  /** Description of the work */
  description: string;
  /** URL of the work image */
  imageUrl: string;
  /** Name of the work */
  name: string;
  /** List of tags associated with the work */
  tags: FetchSharedWorkTag[];
  /** url scan of the work */
  url: string;
}
