/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export interface FetchSharedWorkOwner {
  /** Creation date of the owner account */
  createdAt: string;
  /** Unique identifier of the owner */
  id: string;
  /** URL of the owner image */
  imageUrl: string;
  /** Name of the owner */
  name: string;
}
