/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export interface FetchSharedWorkTag {
  /** Color of the tag */
  color: string;
  /** Unique identifier of the tag */
  id: string;
  /** Name of the tag */
  name: string;
}
