/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type LoggerControllerHealthCheck200Info = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;
