/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { NotificationHttpContent } from "./notificationHttpContent";

export interface NotificationHttp {
	content: NotificationHttpContent;
	id: string;
	readAt: string;
}
