/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export interface OwnerModel {
  createdAt: string;
  /** @nullable */
  imageUrl: string | null;
  name: string;
}
