/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type RefreshStatus = typeof RefreshStatus[keyof typeof RefreshStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshStatus = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
} as const;
