/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { SyncDetailsModel } from './syncDetailsModel';
import type { WorkModel } from './workModel';

export interface ScrappingReportItemModel {
  syncDetails: SyncDetailsModel;
  work: WorkModel;
}
