/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { _SharedCustomListModelTypename } from './_sharedCustomListModelTypename';
import type { OwnerModel } from './ownerModel';
import type { WorkHttp } from './workHttp';

export interface SharedCustomListModel {
  /** */
  readonly __typename: _SharedCustomListModelTypename;
  description?: string;
  id: string;
  owner: OwnerModel;
  title: string;
  works: WorkHttp[];
}
