/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type SyncDetailsModelStatus = typeof SyncDetailsModelStatus[keyof typeof SyncDetailsModelStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SyncDetailsModelStatus = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
  IDLE: 'IDLE',
} as const;
