/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { SyncDetailsModelStatus } from './syncDetailsModelStatus';

export interface SyncDetailsModel {
  createdAt: string;
  id: string;
  /** @nullable */
  message: string | null;
  status: SyncDetailsModelStatus;
  updatedAt: string;
}
