/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type UpdateUserRoleDtoRole = typeof UpdateUserRoleDtoRole[keyof typeof UpdateUserRoleDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserRoleDtoRole = {
  ADMIN: 'ADMIN',
  USER: 'USER',
  SUBSCRIBED_USER: 'SUBSCRIBED_USER',
} as const;
