/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export interface UpdateCustomListDto {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  worksId?: string[] | null;
}
