/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type UserDataRole = typeof UserDataRole[keyof typeof UserDataRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDataRole = {
  ADMIN: 'ADMIN',
  USER: 'USER',
  SUBSCRIBED_USER: 'SUBSCRIBED_USER',
} as const;
