/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { UserHttpRole } from './userHttpRole';
import type { UserHttpTrialQuoteLimit } from './userHttpTrialQuoteLimit';

export interface UserHttp {
  /** @nullable */
  avatarImageUrl: string | null;
  email: string;
  emailConfirmed: boolean;
  finishedWorksCount: number;
  id: string;
  isTelegramSubscriber: boolean;
  name: string;
  notionDatabaseId?: string;
  readingWorksCount: number;
  role: UserHttpRole;
  /** @nullable */
  trialQuoteLimit: UserHttpTrialQuoteLimit;
}
