/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { UserDataRole } from './userDataRole';

export interface UserData {
  createdAt: string;
  email: string;
  id: string;
  name: string;
  role: UserDataRole;
  /** @nullable */
  updatedAt: string | null;
}
