/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { WorkControllerListUserWorksPagedLimit } from './workControllerListUserWorksPagedLimit';
import type { WorkControllerListUserWorksPagedStatus } from './workControllerListUserWorksPagedStatus';
import type { WorkControllerListUserWorksPagedCategory } from './workControllerListUserWorksPagedCategory';

export type WorkControllerListUserWorksPagedParams = {
limit: WorkControllerListUserWorksPagedLimit;
status?: WorkControllerListUserWorksPagedStatus;
search?: string;
tagId?: string;
category?: WorkControllerListUserWorksPagedCategory;
page?: number;
};
