/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export interface WorkModel {
  /** @nullable */
  alternativeName: string | null;
  category: string;
  /** @nullable */
  chapter: number | null;
  id: string;
  /** @nullable */
  imageUrl: string | null;
  name: string;
  /** @nullable */
  nextChapter: number | null;
  slug: string;
  status: string;
  url: string;
}
