/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { WorkControllerCompleteInfoCategory } from './workControllerCompleteInfoCategory';

export type WorkControllerCompleteInfoParams = {
/**
 * The category of the work
 */
category: WorkControllerCompleteInfoCategory;
/**
 * The name of the work
 */
name: string;
};
