/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { WorkModelPagedNextPage } from './workModelPagedNextPage';
import type { WorkHttp } from './workHttp';

export interface WorkModelPaged {
  /** @nullable */
  nextPage: WorkModelPagedNextPage;
  totalOfPages: number;
  works: WorkHttp[];
}
