/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type WorkControllerListUserWorksPagedCategory = typeof WorkControllerListUserWorksPagedCategory[keyof typeof WorkControllerListUserWorksPagedCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkControllerListUserWorksPagedCategory = {
  ANIME: 'ANIME',
  MANGA: 'MANGA',
} as const;
