/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type WorkControllerListUserWorksStatus =
	(typeof WorkControllerListUserWorksStatus)[keyof typeof WorkControllerListUserWorksStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkControllerListUserWorksStatus = {
	unread: "unread",
	read: "read",
	finished: "finished",
	favorites: "favorites",
} as const;
