/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type WorkControllerListUserWorksPagedStatus =
	(typeof WorkControllerListUserWorksPagedStatus)[keyof typeof WorkControllerListUserWorksPagedStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkControllerListUserWorksPagedStatus = {
	unread: "unread",
	read: "read",
	finished: "finished",
	favorites: "favorites",
} as const;
