/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */
import type { WorkCalendarRowModelCategory } from './workCalendarRowModelCategory';
import type { WorkCalendarRowModelStatus } from './workCalendarRowModelStatus';

export interface WorkCalendarRowModel {
  category: WorkCalendarRowModelCategory;
  chapter: number;
  chapters: number;
  /** @nullable */
  description: string | null;
  /** @nullable */
  imageId: string | null;
  /** @nullable */
  imageUrl: string | null;
  name: string;
  /** @nullable */
  nextChapter: number | null;
  status: WorkCalendarRowModelStatus;
}
