/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type WorkHttpCategory =
	(typeof WorkHttpCategory)[keyof typeof WorkHttpCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkHttpCategory = {
	ANIME: "ANIME",
	MANGA: "MANGA",
} as const;
