/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Okami API
 * The Okami rest api
 * OpenAPI spec version: 1.0
 */

export type WorkCalendarRowModelStatus = typeof WorkCalendarRowModelStatus[keyof typeof WorkCalendarRowModelStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkCalendarRowModelStatus = {
  READ: 'READ',
  UNREAD: 'UNREAD',
  FINISHED: 'FINISHED',
  DROPPED: 'DROPPED',
} as const;
